apiVersion: v1
kind: Pod
metadata:
  name: ascii-artify
  labels:
    app: ascii-artify
spec:
  containers:
    - name: ascii-artify
      image: ekasyan/asciiartify:v1.0.2
      ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ascii-artify-svc
spec:
  selector:
    app: ascii-artify
  type: NodePort
  ports:
    - name: http
      nodePort: 30950
      targetPort: 8000
      port: 8000
