apiVersion: v1
kind: Service
metadata:
  labels:
    app: ascii-artify
  name: ascii-artify
spec:
  ports:
    - name: 8000-8000
      nodePort: 30080
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: ascii-artify
  type: NodePort

